Upgrade style app (#414)
* Remove bulma and sprockets config

- [x] Remove simple_form bulma, and update simple_form initializer

* Add ViteRails, trix editor, fontawesome

Links:
  - https://vite-ruby.netlify.app/guide/plugins.html
  - https://github.com/ElMassimo/vite_ruby/tree/main/vite-plugin-rails

* Replace js and style tag helpers

* Disable specs temporarily

* Install tailwind and config

* Add tailwind template

Big thanks to https://flowbite.com

    gh repo clone themesberg/flowbite-admin-dashboard

Links:
  - https://github.com/themesberg/flowbite
  - https://tailwindcss.com/

* Add tailwind template

Big thanks to https://flowbite.com

    gh repo clone themesberg/flowbite-admin-dashboard

Links:
  - https://github.com/themesberg/flowbite
  - https://tailwindcss.com/

* Add model table

* Remove spec views

* Watch files that include tailwind

* Use block at the views

* Update locales

I'll remove duplication

* Update simple_form input style

* Update date field

* Translate model at form buttons

* Match button style

* Fix: Scope patients per hospital

* Scope patients list per hospital

* Validate patient_id at appoinment save

* Scope patients by hospital when creating appoinment

Select patient if is in the current hospital

* Add simple_form hints

* Clean appoinments form

* Fix attachment tailwind css field

* Update Hospitalization form

* Update patient_referral form

* Simplify forms

* Update referred_doctor form

* Remove edit Hospital (temporal)

* Move action buttons

* Remove.js.erb files

* Update patient/show page

* Improve form inputs

* Improve appoinment show page

* Improve hospitalization show page

* Improve referred doctor show page

* Update devise sign in

- [x] Update flash messages style

* Add sectio's title

* Update README

* Standarize padding

* Use section's title partial

* Fix padding on flash messages

* Improve css utilization, improve index, improve title on forms

* Skip failing tests

* Set Ruby version locally

* Fix hover rows on light theme mode

* Use grid on form fields

* Decrease space between inputs

* Update Hospital main page

* Add sidebar icons

* Add buttons icon

* Fix trix buttons when dark mode

* Fix style on views

* Focus search field

* Move css and js files

* Add tooltip

* Update and fix some system tests

* Update patient system test

* Fix and upadte referred doctor system test

* Add ApplicationHelper tests

* Remove unused helper and trying to increase code coverage

* Add active sidebar link helper

* Remove medical_consultation

* Add address test

* Set light theme by default (#435)

I'll add a button to toggle the theme but right now it's not a priority,
so, will check it later.

* Replace paginate gem (#436)

* Remove Kaminari

* Add Pagy

* Paginate by 10 items

* Remove unused code

* Use Node.js v20 (#437)

* Use Node.js v20

* Update Node.js CI

* add stimulus (#438)

* Install stimulus

* Add mi frist stimulus controller: resize_field_controller

I hope I did a good pattern here

* Fix system specs

```ruby
NoMethodError:
  undefined method `feature' for RSpec::ExampleGroups::MedicalConsultationsFlow:Class
  ./spec/system/appoinments_spec.rb:8:in `block in <top (required)>'
  ./spec/system/appoinments_spec.rb:3:in `<top (required)>'
```

* migrate focus to stimulus (#439)

* Some improvements

* Move search.js to focus field stimulus controller

* Migrate sidebar toggler to stimulus (#440)

I'm really enjoying working with Stimulus. It's a great way to add
interactivity to a Rails app without having to write a lot of custom JS.

* add rspec request type

* Fix sidebar background on desktop

* Use single single quotes on js files

* Calculate IMC (#441)

* Fix upload appoinment files (#442)

We should include multiple: true when is a has many relationship

    = f.input :files, input_html: { multiple: true }

* update i18n views (#443)

* Update i18n views

* hospitalizations

* update patient_referral

* Updapte i18n referred_doctor

* Hospitals i18n (#444)