Fix system specs
```ruby
NoMethodError:
  undefined method `feature' for RSpec::ExampleGroups::MedicalConsultationsFlow:Class
  ./spec/system/appoinments_spec.rb:8:in `block in <top (required)>'
  ./spec/system/appoinments_spec.rb:3:in `<top (required)>'
```